name: 'wranglerDynamic'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  template:
    description: 'The template to use'
    required: false
    default: 'wrangler.toml.template'
  myToken:
    description: 'The token to use'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: node20
  main: dist/index.js
